title: <p align="center"> Diego Rodrigues </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1RmB61BYQTdf8CV9-u8YzMtNbAAWMQfKZ0Pp4OfQjPxk/edit?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/diegoaorodrigues/">LinkedIn</a> |
  <a href="https://github.com/DiegoAlves-data">GitHub</a> |
  <a href="https://medium.com/@diegoalvesteo">Medium</a>
  </p>
  
  <p align="justify">
  I am a data scientist with a focus on business intelligence and growth marketing, experienced with Python programming.
  <br><br>
  I am currently development my skills on Machine Learning and Artificial Intelligence.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics:  # Google Analytics tracking ID
